// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSetting(arg1:string):Promise<void>;

export function GetFilePath():Promise<string>;

export function GetSetting(arg1:string):Promise<any>;

export function OpenFileBytes(arg1:string):Promise<Array<number>>;

export function ReadBytes(arg1:string):Promise<Array<number>>;

export function SaveFileBytes(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveFilePath(arg1:string):Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function Version():Promise<string>;
