// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSetting(arg1) {
  return window['go']['main']['App']['ClearSetting'](arg1);
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function OpenFileBytes(arg1) {
  return window['go']['main']['App']['OpenFileBytes'](arg1);
}

export function ReadBytes(arg1) {
  return window['go']['main']['App']['ReadBytes'](arg1);
}

export function SaveFileBytes(arg1, arg2) {
  return window['go']['main']['App']['SaveFileBytes'](arg1, arg2);
}

export function SaveFilePath(arg1) {
  return window['go']['main']['App']['SaveFilePath'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
