// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDirectory(arg1:string):Promise<string>;

export function CacheDirectory(arg1:string):Promise<string>;

export function ClearSetting(arg1:string):Promise<void>;

export function GetFilePath(arg1:Array<string>,arg2:Array<string>):Promise<string>;

export function GetFilesInDir(arg1:string):Promise<Array<string>>;

export function GetSetting(arg1:string):Promise<any>;

export function OpenFileBytes(arg1:string):Promise<Array<number>>;

export function ReadBytes(arg1:string):Promise<Array<number>>;

export function SaveFileBytes(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveFilePath(arg1:string):Promise<string>;

export function SetRichPresenceDetails(arg1:string):Promise<void>;

export function SetRichPresenceState(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function StartRichPresence():Promise<void>;

export function StopRichPresence():Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function UpdateRichPresence():Promise<void>;

export function Version():Promise<string>;
