// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Load(arg1) {
  return window['go']['main']['App']['Load'](arg1);
}

export function OpenFileBytes(arg1) {
  return window['go']['main']['App']['OpenFileBytes'](arg1);
}

export function ReadBytes(arg1) {
  return window['go']['main']['App']['ReadBytes'](arg1);
}

export function Save(arg1, arg2) {
  return window['go']['main']['App']['Save'](arg1, arg2);
}
