// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDirectory(arg1) {
  return window['go']['main']['App']['AppDirectory'](arg1);
}

export function CacheDirectory(arg1) {
  return window['go']['main']['App']['CacheDirectory'](arg1);
}

export function ClearSetting(arg1) {
  return window['go']['main']['App']['ClearSetting'](arg1);
}

export function GetFilePath(arg1, arg2) {
  return window['go']['main']['App']['GetFilePath'](arg1, arg2);
}

export function GetFileSavePath(arg1, arg2) {
  return window['go']['main']['App']['GetFileSavePath'](arg1, arg2);
}

export function GetFilesInDir(arg1) {
  return window['go']['main']['App']['GetFilesInDir'](arg1);
}

export function GetOSSeparator() {
  return window['go']['main']['App']['GetOSSeparator']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function OpenFileBytes(arg1) {
  return window['go']['main']['App']['OpenFileBytes'](arg1);
}

export function ReadBytes(arg1) {
  return window['go']['main']['App']['ReadBytes'](arg1);
}

export function SaveFileBytes(arg1, arg2) {
  return window['go']['main']['App']['SaveFileBytes'](arg1, arg2);
}

export function SaveFilePath(arg1) {
  return window['go']['main']['App']['SaveFilePath'](arg1);
}

export function SetRichPresenceDetails(arg1) {
  return window['go']['main']['App']['SetRichPresenceDetails'](arg1);
}

export function SetRichPresenceState(arg1) {
  return window['go']['main']['App']['SetRichPresenceState'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StartRichPresence() {
  return window['go']['main']['App']['StartRichPresence']();
}

export function StopRichPresence() {
  return window['go']['main']['App']['StopRichPresence']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function UpdateRichPresence() {
  return window['go']['main']['App']['UpdateRichPresence']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
